version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: my_postgres_db
      POSTGRES_USER: OscarRapale
      POSTGRES_PASSWORD: Vanezephyr1126
    networks:
      - mynetwork

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: oscarrapale@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Vanezephyr1126
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "8080:80"

networks:
  mynetwork:
